--NOTE: time ran out. created tables and begun query work

CREATE TABLE Products(
ID int primary key identity,
Name NVARCHAR(255),
Price money
);

CREATE TABLE Customers(
ID int primary key Identity,
FirstName NVARCHAR(255),
LastName NVARCHAR(255),
CardNumber int check(CardNumber>999999999999999 AND CardNumber<10000000000000000) --checks for 16 digits
);

CREATE TABLE Orders(
ID int primary key identity,
ProductID int not null,
CustomerID int not null,
Foreign key (ProductID) references Products(ID),
Foreign key (CustomerID) references Customers(ID)
);

-- add at least 3 records into each table.


-- add product iPhone priced at $200. 
INSERT INTO Products VALUES([Name] = 'iPhone', Price = 200);

-- add customer Tina Smith. 

-- create order for Tina Smith bought an iPhone. 

-- report all orders by Tina Smith. 
SELECT * from Orders as o, Customers as c where (o.CustomerID=c.ID);

-- report all revenue generated by sales of iPhone. 


-- increase the price of iPhone to $250.

