--add at least 3 records into each table. 
--add employee Tina Smith.  
--add department Marketing.


--Insert Departments
INSERT INTO Department
Values ('Marketing', 'Virginia');

INSERT INTO Department
Values ('Business', 'Virginia');

INSERT INTO Department
Values ('Ingeniering', 'Virginia');


--Insert Employees
INSERT INTO Employee
Values ('Tina', 'Smith','123456789', 1);

INSERT INTO Employee
Values ('John', 'Smith','235648958', 2);

INSERT INTO Employee
Values ('Stephanie', 'Burgos','645258794', 3);


--Insert Employee Details
INSERT INTO EmpDetails
Values (1, '$15,000', 'Street 12345','','Orocovis','PR', '');

INSERT INTO EmpDetails
Values (2, '$20,000', 'Street 6456','','San Juan','PR', '');

INSERT INTO EmpDetails
Values (3, '$30,000', 'Street 7894','','Aguadilla','PR', '');


--list all employees in Marketing.
SELECT * FROM Employee.e, Department.d
WHERE e.DeptID = 1

--report total salary of Marketing.
SELECT SUM(ed.Salary)
FROM EmpDetails.ed, Employee.e
WHERE e.DeptID = 1


--report total employees by department. 
SELECT COUNT(e.ID)
FROM Employee.e, Department.d
WHERE d.ID IN (SELECT e.ID FROM Employee);

--increase salary of Tina Smith to $90,000
UPDATE EmpDetails
SET Salary = '$90,000'
WHERE EmployeeID = 1;






--Insert Products

INSERT INTO Products
Values ('IPhone', '$200');

INSERT INTO Products
Values ('Samsung Galaxy 7', '$180');

INSERT INTO Department
Values ('LG G4', '$150');

--Insert Customer
INSERT INTO Customer
Values ('Tina', 'Smith','123456789');

INSERT INTO Customer
Values ('John', 'Smith','235648958');

INSERT INTO Customer
Values ('Stephanie', 'Burgos','645258794');

--Insert Orders
INSERT INTO Orders
Values (1,1);

INSERT INTO Orders
Values (2,2);

INSERT INTO Orders
Values (3,3);


--create order for Tina Smith bought an iPhone.
INSERT INTO Orders
Values (1,1);

--report all orders by Tina Smith. 
SELECT *
FROM Orders.o, Customer.c, Products.p
WHERE o.ProductID = p.ID AND o.CustomerID = c.ID


--report all revenue generated by sales of iPhone
SELECT *
FROM Orders
WHERE ProductID = 1

--increase the price of iPhone to $250.
UPDATE Products
SET Price = '250'
WHERE ID = 1;