CREATE DATABASE ChallengeStore;
GO

CREATE SCHEMA Store;
GO

CREATE TABLE Products
(
	ID INT PRIMARY KEY,
	Name NVARCHAR(128) NOT NULL,
	Price INT NOT NULL
);

CREATE TABLE Customers
(
	ID INT PRIMARY KEY,
	FirstName NVARCHAR(128) NOT NULL,
	LastName NVARCHAR(128) NOT NULL,
	CardNumber NVARCHAR(128) NOT NULL,
);

CREATE TABLE Orders
(
	ID INT PRIMARY KEY,
	ProductID INT FOREIGN KEY REFERENCES Products(ID) NOT NULL,
	CustomerID INT FOREIGN KEY REFERENCES Customers(ID) NOT NULL,
);

-- add at least 3 records into each table.

INSERT INTO Products
VALUES (1, 'Computer', 500);

INSERT INTO Products
VALUES (2, 'iPhone X', 1000);

INSERT INTO Products
VALUES (3, 'Beats Headphones', 350);

INSERT INTO Customers
VALUES (101, 'Donald', 'Trump', '1234849384957493');

INSERT INTO Customers
VALUES (102, 'Melania', 'Trump', '6653265987563254');

INSERT INTO Customers
VALUES (103, 'Eric', 'Trump', '7563256359755963');

INSERT INTO Orders
VALUES (201, 1, 101)

INSERT INTO Orders
VALUES (202, 2, 102)

INSERT INTO Orders
VALUES (203, 3, 103)


-- add product iPhone priced at $200.
INSERT INTO Products
VALUES (4, 'iPhone', 200);

-- add customer Tina Smith.
INSERT INTO Customers
VALUES (104, 'Tina', 'Smith', 8569563215632596);

-- create order for Tina Smith bought an iPhone.
INSERT INTO Orders
VALUES (204, 4, 104);

-- report all orders by Tina Smith.
SELECT *
FROM ORDERS AS o, Customers AS c
WHERE o.CustomerID = c.ID AND c.FirstName = 'Tina' AND c.LastName = 'Smith';

-- report all revenue generated by sales of iPhone.
SELECT COUNT(*) * 200
FROM Orders as o
WHERE o.ProductID = 4;


-- increase the price of iPhone to $250.
UPDATE Products
SET Price = '250'
WHERE Name = 'iPhone';
